package com.filestech.appmanager.data.repository

import com.filestech.appmanager.data.local.db.dao.PermissionSnapshotDao
import com.filestech.appmanager.data.local.db.entity.PermissionSnapshotEntity
import com.filestech.appmanager.domain.model.PermissionSnapshot
import com.filestech.appmanager.domain.model.SnapshotStats
import com.filestech.appmanager.domain.repository.PermissionSnapshotRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Room-backed [PermissionSnapshotRepository]. All entity↔domain mapping is
 * confined to this file — the domain layer stays androidx-free.
 */
@Singleton
class PermissionSnapshotRepositoryImpl @Inject constructor(
    private val dao: PermissionSnapshotDao,
) : PermissionSnapshotRepository {

    override suspend fun getLatest(packageName: String, permission: String): PermissionSnapshot? =
        dao.getLatest(packageName, permission)?.toDomain()

    override suspend fun insert(snapshot: PermissionSnapshot) {
        dao.insert(snapshot.toEntity())
    }

    override fun observeDriftRows(sinceMs: Long): Flow<List<PermissionSnapshot>> =
        dao.observeDrifts(sinceMs).map { rows -> rows.map { it.toDomain() } }

    override suspend fun count(): Int = dao.count()

    override fun observeStats(): Flow<SnapshotStats> = dao.observeStats().map { row ->
        SnapshotStats(
            distinctPackages    = row.distinctPackages,
            distinctPermissions = row.distinctPermissions,
            lastCapturedAt      = row.lastCapturedAt,
        )
    }

    override suspend fun purgeOlderThan(cutoffMs: Long): Int = dao.purgeOlderThan(cutoffMs)

    override suspend fun deleteAll(): Int = dao.deleteAll()

    override suspend fun deleteByPackage(packageName: String): Int =
        dao.deleteByPackage(packageName)

    private fun PermissionSnapshotEntity.toDomain(): PermissionSnapshot = PermissionSnapshot(
        packageName = packageName,
        permission  = permission,
        granted     = granted,
        capturedAt  = capturedAt,
    )

    private fun PermissionSnapshot.toEntity(): PermissionSnapshotEntity = PermissionSnapshotEntity(
        // id auto-generated by Room (PK INTEGER AUTOINCREMENT)
        packageName = packageName,
        permission  = permission,
        granted     = granted,
        capturedAt  = capturedAt,
    )
}
