#!/usr/bin/env python3
"""Assert the permissions of the MERGED release manifest against the reviewed allowlist.

Why this exists
---------------
"No Internet permission" is written on files-tech.com, in the README and in PRIVACY.md. A promise no
build checks is an intention, so this script turns it into a build constraint.

The precedent is in the portfolio: Agenda Tech PUBLISHED an APK carrying `ACCESS_NETWORK_STATE`,
pulled transitively by `androidx.work`, and nobody noticed before a later audit.

Two traps this script avoids
----------------------------
1. **The source manifest is not evidence.** Libraries add permissions at merge time: the source
   manifest of this app declares seven, the merged release manifest carries twelve (measured
   2026-10-08). Only the merged manifest decides what the published APK asks for.
2. **`<uses-permission>` can span several lines.** A line-based grep misses an element whose
   `android:name` sits on its own line, which is a shape the merge produces. This parses the XML.

What is forbidden, and what is only reviewed
--------------------------------------------
`INTERNET` is the permission that lets an app open a socket, and the one the public promise names.
It is refused whatever ALLOWED says.

`ACCESS_NETWORK_STATE` is NOT forbidden here, unlike in Agenda Tech and Notes Tech: WorkManager adds
it, and PRIVACY.md documents it (it reads whether a network is present; without `INTERNET` it cannot
use one). It sits in the reviewed allowlist like every other transitive permission. Decided on
2026-10-08; removing it would be a change to the app, not to its CI.

Usage
-----
    python3 tools/check-manifest-permissions.py [path-to-merged-manifest]

The path may also be the manifest of a built APK, as printed by
`apkanalyzer manifest print <apk>`: the CI checks both, the merged manifest and the APK that ships.

Exit code 0 when the manifest matches the allowlist exactly, 1 otherwise. Prints GitHub Actions
`::error::` annotations when run under CI, plain text otherwise.
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

# The Windows console is cp1252: a non-ASCII character in a message would otherwise crash the script,
# that is, report a FAILED check when the check succeeded.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ANDROID_NS = "http://schemas.android.com/apk/res/android"

DEFAULT_MANIFEST = os.path.join(
    "app", "build", "intermediates", "merged_manifest", "release",
    "processReleaseMainManifest", "AndroidManifest.xml",
)

# The release applicationId. The debug manifest carries `.debug`: checking the package proves the file
# read is the RELEASE manifest of this app, not merely some manifest that happens to parse.
EXPECTED_PACKAGE = "com.filestech.appmanager"

# Must NEVER reach the APK, whatever the allowlist says. Kept apart from ALLOWED so the failure
# message can say WHY, not only "unexpected".
FORBIDDEN = {
    "android.permission.INTERNET",
}

# Every permission the reviewed APK is expected to carry: the table of PRIVACY.md §3, no more, no
# less. An allowlist and not only a denylist, because a permission arriving transitively must be a
# deliberate, reviewed act.
#
# Adding an entry here is a two-part change: the permission must ALSO be documented in the table of
# PRIVACY.md and PRIVACY.fr.md. That pairing is the point of the list.
ALLOWED = {
    # Declared in app/src/main/AndroidManifest.xml.
    "android.permission.QUERY_ALL_PACKAGES",
    "android.permission.PACKAGE_USAGE_STATS",
    "android.permission.REQUEST_DELETE_PACKAGES",
    # v0.5.1: without it, the system installer refused every quarantine restore.
    "android.permission.REQUEST_INSTALL_PACKAGES",
    "android.permission.GET_PACKAGE_SIZE",
    "android.permission.KILL_BACKGROUND_PROCESSES",
    "android.permission.POST_NOTIFICATIONS",
    # Transitive, from androidx.work, which runs the periodic scan.
    "android.permission.WAKE_LOCK",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.ACCESS_NETWORK_STATE",
    # Signature level, generated by androidx.core for its own non-exported receivers. The release
    # applicationId has no suffix, so the full name is fixed.
    "com.filestech.appmanager.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
}

IN_CI = os.environ.get("GITHUB_ACTIONS") == "true"


def fail(lines: list[str]) -> None:
    prefix = "::error::" if IN_CI else "ERROR: "
    for line in lines:
        print(f"{prefix}{line}")


def parse(manifest_path: str) -> tuple[ET.Element, set[str]]:
    """The manifest root and every permission it requests, parsed as XML rather than grepped."""
    root = ET.parse(manifest_path).getroot()
    names = set()
    # Every spelling, matched by prefix: `<uses-permission-sdk-23>` grants the same capability on
    # API 23+, and the platform parser still accepts its pre-release alias `<uses-permission-sdk-m>`.
    # aapt2 rejects the alias today (measured 2026-10-08: "unexpected element"), but the merger keeps
    # it, so this guard does not rely on aapt2 to close that door.
    for element in root.iter():
        if element.tag.startswith("uses-permission"):
            name = element.get(f"{{{ANDROID_NS}}}name")
            if name:
                names.add(name)
    return root, names


def main(argv: list[str]) -> int:
    manifest_path = argv[1] if len(argv) > 1 else DEFAULT_MANIFEST

    if not os.path.isfile(manifest_path):
        fail([
            f"merged manifest not found: {manifest_path}",
            "run first: ./gradlew :app:processReleaseMainManifest",
        ])
        return 1

    try:
        root, found = parse(manifest_path)
    except ET.ParseError as error:
        fail([f"merged manifest unreadable ({manifest_path}): {error}"])
        return 1

    if root.tag != "manifest" or root.find("application") is None:
        fail([
            f"{manifest_path} is not an application manifest -",
            "this is a failure of the check, not an absence of permissions.",
        ])
        return 1

    package = root.get("package")
    if package != EXPECTED_PACKAGE:
        fail([
            f"{manifest_path} is not the release manifest of {EXPECTED_PACKAGE} (package={package}) -",
            "this is a failure of the check, not a verdict on permissions.",
        ])
        return 1

    if not found:
        # An empty result is a broken check, never a clean bill of health: the app cannot list the
        # installed packages without QUERY_ALL_PACKAGES.
        fail([
            f"no permission found in {manifest_path} -",
            "this is a failure of the check, not an absence of permissions.",
        ])
        return 1

    print(f"Manifest: {manifest_path}")
    print(f"applicationId: {package}")
    print(f"Permissions ({len(found)}):")
    for name in sorted(found):
        mark = "ok " if name in ALLOWED else "!! "
        print(f"  {mark}{name}")

    problems: list[str] = []

    forbidden_present = sorted(found & FORBIDDEN)
    if forbidden_present:
        problems.append("NETWORK permission in the merged release manifest:")
        problems += [f"  {name}" for name in forbidden_present]
        problems.append(
            "App Manager Tech publicly promises \"no Internet permission\". Either the dependency "
            "that pulled it goes, or it is removed with tools:node=\"remove\" and the removal "
            "justified.",
        )

    unexpected = sorted(found - ALLOWED - FORBIDDEN)
    if unexpected:
        problems.append("Permission(s) outside the reviewed list:")
        problems += [f"  {name}" for name in unexpected]
        problems.append(
            "A permission arriving transitively must be a deliberate act: add it to ALLOWED in this "
            "script AND to the table of PRIVACY.md and PRIVACY.fr.md, or drop the dependency.",
        )

    # A permission that disappears is not a failure, but it must not go unnoticed: the list and
    # PRIVACY.md would then both describe an APK that no longer exists.
    missing = sorted(ALLOWED - found)
    if missing:
        print()
        print("Note - expected but absent from the merged manifest:")
        for name in missing:
            print(f"  {name}")
        print("  Remove them from ALLOWED and from PRIVACY.md if the removal is intended.")

    if problems:
        print()
        fail(problems)
        return 1

    print()
    print("OK: no INTERNET, and no permission outside the reviewed list.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
